"use client";
import { FormEvent, useState } from "react";
import { motion } from "framer-motion";
import { ArrowRight, Building2, CheckCircle2, Loader2, Mail, Send, ShieldCheck, Sparkles } from "lucide-react";
import Link from "next/link";
import styles from "./contact.module.css";

export default function ContactPage() {
  const [submitted,setSubmitted]=useState(false); const [submitting,setSubmitting]=useState(false); const [error,setError]=useState("");
  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSubmitting(true); setError(""); const form=event.currentTarget; const fd=new FormData(form);
    const payload={name:fd.get("name"),email:fd.get("email"),company:fd.get("company"),businessType:fd.get("businessType"),teamSize:fd.get("teamSize"),priority:fd.get("priority"),message:fd.get("message"),website:fd.get("website")};
    try { const response=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const data=await response.json(); if(!response.ok) throw new Error(data.message||"Something went wrong."); form.reset(); setSubmitted(true); }
    catch(err){ setError(err instanceof Error?err.message:"Unable to submit your request right now."); } finally { setSubmitting(false); }
  }
  return <main className={styles.page}>
    <div className={styles.background} aria-hidden="true"><div className={styles.grid}/><div className={styles.glowOne}/><div className={styles.glowTwo}/></div>
    <header className={styles.navbar}><Link className={styles.brand} href="/"><span className={styles.brandMark}>S</span><span>SYNQO <strong>AI</strong></span></Link><nav className={styles.navLinks}><Link href="/">Home</Link><Link href="/products">AI Employee</Link><Link href="/services">Services</Link><Link href="/about">About</Link><Link className={styles.activeLink} href="/contact">Early Access</Link></nav><Link className={styles.navButton} href="/contact">Request Access<ArrowRight size={17}/></Link></header>
    <section className={styles.hero}><motion.div initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.65}} className={styles.heroContent}><div className={styles.eyebrow}><Sparkles size={17}/>Synqo AI Employee Early Access</div><h1>Bring an AI Employee<span>into your business.</span></h1><p>Tell us about your business and the repetitive work you want to automate. We are onboarding early businesses as Synqo AI Employee moves through development.</p></motion.div></section>
    <section className={styles.contactSection}><motion.div initial={{opacity:0,x:-30}} whileInView={{opacity:1,x:0}} viewport={{once:true,amount:.2}} transition={{duration:.65}} className={styles.formCard}><div className={styles.formHeading}><span>JOIN EARLY ACCESS</span><h2>Tell us about your business.</h2><p>Share a few details so we can understand where an AI Employee could be most useful for your team.</p></div>
      {submitted?<div className={styles.successBox}><CheckCircle2 size={32}/><div><h3>Early access request received.</h3><p>Thanks for your interest in Synqo AI Employee. We will review your information and contact suitable early-access businesses.</p></div></div>:
      <form className={styles.form} onSubmit={handleSubmit}><input name="website" tabIndex={-1} autoComplete="off" style={{display:"none"}} aria-hidden="true" />
        <div className={styles.fieldGrid}><label><span>Full name</span><input name="name" type="text" placeholder="Your name" required/></label><label><span>Business email</span><input name="email" type="email" placeholder="you@business.com" required/></label></div>
        <div className={styles.fieldGrid}><label><span>Business name</span><input name="company" type="text" placeholder="Your company" required/></label><label><span>Business type</span><select name="businessType" defaultValue="" required><option value="" disabled>Select business type</option><option>Professional Services</option><option>Home Services</option><option>Real Estate</option><option>Clinic / Healthcare</option><option>Salon / Beauty</option><option>Restaurant / Hospitality</option><option>E-commerce</option><option>Agency</option><option>Other</option></select></label></div>
        <div className={styles.fieldGrid}><label><span>Team size</span><select name="teamSize" defaultValue="" required><option value="" disabled>Select team size</option><option>Just me</option><option>2–5 people</option><option>6–20 people</option><option>21–50 people</option><option>50+ people</option></select></label><label><span>Main priority</span><select name="priority" defaultValue="" required><option value="" disabled>What should AI handle?</option><option>Customer enquiries</option><option>Lead capture</option><option>Appointments</option><option>Follow-ups</option><option>Business email</option><option>Multiple workflows</option></select></label></div>
        <label><span>What would you like your AI Employee to handle?</span><textarea name="message" rows={7} placeholder="Example: answer customer questions, qualify leads, book appointments and follow up automatically." required/></label>
        {error&&<div style={{padding:"14px 16px",border:"1px solid rgba(248,113,113,.25)",borderRadius:"12px",background:"rgba(127,29,29,.12)",color:"#fca5a5",fontSize:"13px",lineHeight:1.6}}>{error}</div>}
        <button className={styles.submitButton} type="submit" disabled={submitting}>{submitting?<><span>Sending...</span><Loader2 size={18} className="animate-spin"/></>:<>Request Early Access<Send size={18}/></>}</button><div className={styles.formNote}><ShieldCheck size={16}/>Your information will only be used for Synqo AI product and early-access communication.</div>
      </form>}
    </motion.div><motion.aside initial={{opacity:0,x:30}} whileInView={{opacity:1,x:0}} viewport={{once:true,amount:.2}} transition={{duration:.65,delay:.1}} className={styles.contactSidebar}><div className={styles.infoCard}><span className={styles.sectionLabel}>SYNQO AI EMPLOYEE</span><div className={styles.infoRow}><div className={styles.infoIcon}><Building2 size={20}/></div><div><strong>Built for modern businesses</strong><span>Designed for businesses that want to reduce repetitive customer-facing work.</span></div></div><div className={styles.infoRow}><div className={styles.infoIcon}><Sparkles size={20}/></div><div><strong>Early-stage product</strong><span>We are currently building and validating the first version with real business workflows.</span></div></div><div className={styles.infoRow}><div className={styles.infoIcon}><Mail size={20}/></div><div><strong>General contact</strong><span>synqoai@yahoo.com</span></div></div></div><div className={styles.whyCard}><span className={styles.sectionLabel}>WHAT IT CAN HELP WITH</span><div className={styles.reasonList}>{["Customer enquiries","Lead capture","Appointment booking","Follow-ups","Business email","Repetitive workflow automation"].map(x=><div key={x}><CheckCircle2 size={17}/>{x}</div>)}</div></div></motion.aside></section>
  </main>;
}
